# Generated by Django 4.1.5 on 2023-01-18 00:52

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_image')),
                ('caption', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='Email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.TextField(blank=True),
        ),
    ]
