# Generated by Django 4.1.5 on 2023-01-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0002_post_profile_email_profile_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Working_at',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
