# Generated by Django 4.1.5 on 2023-01-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blank_profile_pic.jpg', upload_to='post_image'),
        ),
    ]
