# Generated by Django 4.1.5 on 2023-01-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0009_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.TextField(blank=True),
        ),
    ]
