# Generated by Django 4.1.5 on 2023-01-24 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0013_remove_post_image_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='post_image'),
            preserve_default=False,
        ),
    ]
